export const enum Action {
  MINIMIZE_WINDOW = 'MINIMIZE_WINDOW',
  MAXIMIZE_WINDOW = 'MAXIMIZE_WINDOW',
  RESTORE_WINDOW = 'RESTORE_WINDOW',
  CLOSE_WINDOW = 'CLOSE_WINDOW'
}

export const enum DownloadIpcType {
  SET_DOWNLOAD_PATH = 'SET_DOWNLOAD_PATH',
  DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS',
  DOWNLOAD_START = 'DOWNLOAD_START',
  DOWNLOAD_END = 'DOWNLOAD_END'
}

export const enum MiddlewareView {
  CREATE_WINDOW = 'CREATE_WINDOW',
  UPDATE_THEME_COLOR = 'UPDATE_THEME_COLOR'
}

export const enum LyriceAction {
  LYRICE_UPDATE = 'LYRICE_UPDATE',
  LYRICE_UPDATE_RENDER = 'LYRICE_UPDATE_RENDER',
  LYRICE_WIN_CLOSE = 'LYRICE_WIN_CLOSE'
}

export const enum UpdateType {
  UPDATE_INDEX = 'UPDATE_INDEX',
  UPDATE_LYRICE = 'UPDATE_LYRICE',
  UPDATE_PLAYING = 'UPDATE_PLAYING',
  UPDATE_MAGIC = 'UPDATE_MAGIC',
  UPDATE_WIDTH = 'UPDATE_WIDTH'
}

export const enum ReadLocalFile {
  READ_MP3_FROM_PATH = 'READ_MP3_FROM_PATH'
}
