export const enum Action {
  MINIMIZE_WINDOW = 'MINIMIZE_WINDOW',
  MAXIMIZE_WINDOW = 'MAXIMIZE_WINDOW',
  RESTORE_WINDOW = 'RESTORE_WINDOW',
  CLOSE_WINDOW = 'CLOSE_WINDOW',
  CREATE_WINDOW = 'CREATE_WINDOW'
}

export const enum LyriceAction {
  LYRICE_UPDATE = 'LYRICE_UPDATE',
  LYRICE_UPDATE_RENDER = 'LYRICE_UPDATE_RENDER'
}

export const enum UpdateType {
  UPDATE_INDEX = 'UPDATE_INDEX',
  UPDATE_LYRICE = 'UPDATE_LYRICE',
  UPDATE_PLAYING = 'UPDATE_PLAYING',
  UPDATE_MAGIC = 'UPDATE_MAGIC'
}
