export type ConvolutionFile =
  | '原唱'
  | 'AliceInBones'
  | 'BlackSunGarden'
  | 'Car radio close'
  | 'Car radio wide'
  | 'CastilloDeLosTresReyesDelMorro'
  | 'CliffOfTheDawn'
  | 'CornOnTheLeash'
  | 'Erres tube radio.C'
  | 'FatMansMisery'
  | 'FooToFly'
  | 'Fredman_Mono_Vintage30_Solid'
  | 'Fredman_Mono_Vintage30_SPARC'
  | 'Fredman_Mono_Vintage30_Tube'
  | 'GreedSacrifice'
  | 'GreenBasketCase'
  | 'iron box mono'
  | 'IslaMujeresCave'
  | 'LawrenceWelkCave'
  | 'Mono_3DoorTonite_Solid'
  | 'Mono_3DoorTonite_SPARC'
  | 'Mono_3DoorTonite_Tube'
  | 'Mono_AlterYourEyes_Solid'
  | 'Mono_AlterYourEyes_SPARC'
  | 'Mono_AlterYourEyes_Tube'
  | 'Mono_Bushlyerine_Solid'
  | 'Mono_Bushlyerine_SPARC'
  | 'Mono_Bushlyerine_Tube'
  | 'Mono_TheSpringsArentAlright_Solid'
  | 'Mono_TheSpringsArentAlright_SPARC'
  | 'Mono_TheSpringsArentAlright_Tube'
  | 'NaumburgBandshell'
  | 'ScorpYouLikeAHurricane'
  | 'Small portable ambient'
  | 'Small portable'
  | 'Small speaker mono'
  | 'SpoonGarden'
  | 'StanleyParkCliffs'
  | 'SweetChildOfGun'
  | 'ToolPot'
  | 'Very small speaker mono'
  | 'WoodruffLane'
