export const EVENT_SETUP_MENU = 'EVENT_SETUP_MENU'

export const EVENT_APP_SETTING = 'EVENT_APP_SETTING'
export const EVENT_APP_UPDATE = 'EVENT_APP_UPDATE'
export const EVENT_APP_AUTH = 'EVENT_APP_AUTH'

/* Music-Control */
export const EVENT_MUSICCONTROL_PLAY_OR_PAUSE = 'EVENT_MUSICCONTROL_PLAY'
export const EVENT_MUSICCONTROL_NEXT = 'EVENT_MUSICCONTROL_NEXT'
export const EVENT_MUSICCONTROL_PREV = 'EVENT_MUSICCONTROL_PREV'
export const EVENT_MUSICCONTROL_VOLUP = 'EVENT_MUSICCONTROL_VOLUP'
export const EVENT_MUSICCONTROL_VOLDOWN = 'EVENT_MUSICCONTROL_VOLDOWN'
export const EVENT_MUSICCONTROL_LYRICS_OPEN_OR_CLOSE =
  'EVENT_MUSICCONTROL_LYRICS_OPEN_OR_CLOSE'

export const EVENT_MUSICCONTROL_LIKE = 'EVENT_MUSICCONTROL_LIKE'
export const EVENT_MUSICCONTROL_PLAYMODE = 'EVENT_MUSICCONTROL_PLAYMODE'
export const EVENT_MUSICCONTROL_SHUFFLE = 'EVENT_MUSICCONTROL_SHUFFLE'
export const EVENT_MUSICCONTROL_SINGLE_LOOP = 'EVENT_MUSICCONTROL_SINGLE_LOOP'
export const EVENT_MUSICCONTROL_ALL_LOOP = 'EVENT_MUSICCONTROL_ALL_LOOP'

/* Emitter */
export const EVENT_APP_SETTING_EMITTER = 'EVENT_APP_SETTING_EMITTER'
export const EVENT_APP_UPDATE_EMITTER = 'EVENT_APP_SETTING_EMITTER'
export const EVENT_APP_AUTH_EMITTER = 'EVENT_APP_AUTH_EMITTER'

/* Emitter Music Control */
export const EVENT_MUSICCONTROL_PLAY_OR_PAUSE_EMITTER =
  'EVENT_MUSICCONTROL_PLAY_OR_PAUSE_EMITTER'
export const EVENT_MUSICCONTROL_NEXT_EMITTER = 'EVENT_MUSICCONTROL_NEXT_EMITTER'
export const EVENT_MUSICCONTROL_PREV_EMITTER = 'EVENT_MUSICCONTROL_PREV_EMITTER'
export const EVENT_MUSICCONTROL_VOLUP_EMITTER =
  'EVENT_MUSICCONTROL_VOLUP_EMITTER'
export const EVENT_MUSICCONTROL_VOLDOWN_EMITTER =
  'EVENT_MUSICCONTROL_VOLDOWN_EMITTER'

export const EVENT_MUSICCONTROL_LYRICS_OPEN_OR_CLOSE_EMITTER =
  'EVENT_MUSICCONTROL_LYRICS_OPEN_OR_CLOSE_EMITTER'
export const EVENT_MUSICCONTROL_LIKE_EMITTER = 'EVENT_MUSICCONTROL_LIKE_EMITTER'

export const EVENT_MUSICCONTROL_PLAYMODE_EMITTER =
  'EVENT_MUSICCONTROL_PLAYMODE_EMITTER'
export const EVENT_MUSICCONTROL_SHUFFLE_EMITTER =
  'EVENT_MUSICCONTROL_SHUFFLE_EMITTER'
export const EVENT_MUSICCONTROL_SINGLE_LOOP_EMITTER =
  'EVENT_MUSICCONTROL_SINGLE_LOOP_EMITTER'
export const EVENT_MUSICCONTROL_ALL_LOOP_EMITTER =
  'EVENT_MUSICCONTROL_ALL_LOOP_EMITTER'

export const CHANGE_PLAY_MODE_EVENT_MAP = [
  EVENT_MUSICCONTROL_SHUFFLE,
  EVENT_MUSICCONTROL_SINGLE_LOOP,
  EVENT_MUSICCONTROL_ALL_LOOP
]
